TEMPLATE = subdirs

SUBDIRS += \
    adhoc_test \
    adhoccommand_test \
    adhoccommandnote_test \
    amp_test \
    amprule_test \
    base64_test \
    capabilities_test \
    carbons_test \
    chatstatefilter_test \
    clientbase_test \
    connectionbosh_test \
    connectiontcpserver_test \
    dataform_test \
    dataformfield_test \
    dataformitem_test \
    dataformreported_test \
    delayeddelivery_test \
    disco_test \
    discoinfo_test \
    discoitems_test \
    error_test \
    featureneg_test \
    flexoffline_test \
    flexofflineoffline_test \
    forward_test \
    gpgencrypted_test \
    gpgsigned_test \
    inbandbytestream_test \
    inbandbytestreamibb_test \
    iodata_test \
    iq_test \
    jid_test \
    jingleiceudp_test \
    jinglesession_test \
    jinglesessionjingle_test \
    jinglesessionmanager_test \
    lastactivity_test \
    lastactivityquery_test \
    md5_test \
    message_test \
    messageeventfilter_test \
    mucroommuc_test \
    mucroommucadmin_test \
    mucroommucowner_test \
    mucroommucuser_test \
    nickname_test \
    nonsaslauth_test \
    nonsaslauthquery_test \
    oob_test \
    parser_test \
    prep_test \
    presence_test \
    privacymanager_test \
    privacymanagerquery_test \
    privatexml_test \
    pubsubevent_test \
    pubsubmanager_test \
    pubsubmanagerpubsub_test \
    receipt_test \
    registration_test \
    registrationquery_test \
    rostermanager_test \
    rostermanagerquery_test \
    search_test \
    searchquery_test \
    sha_test \
    shim_test \
    simanager_test \
    simanagersi_test \
    stanzaextensionfactory_test \
    subscription_test \
    tag_test \
    tlsgnutls_test \
    uniquemucroomunique_test \
    util_test \
    vcard_test \
    vcardupdate_test \
    xpath_test \
    zlib_test

#client_test \    zlib_perf_test \ stanzaextensionfactory_perf_test \ tag_perf_test \ jid_perf_test \
